# Prefer using `SourcePos` from deno_ast because it abstracts
# away swc's non-zero-indexed based positioning
disallowed-methods = [
  "swc_common::Spanned::span",
  { path = "std::env::current_dir", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::Path::exists", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::Path::canonicalize", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::Path::is_dir", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::Path::is_file", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::Path::is_symlink", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::Path::metadata", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::Path::read_dir", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::Path::read_link", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::Path::symlink_metadata", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::Path::try_exists", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::PathBuf::exists", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::PathBuf::canonicalize", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::PathBuf::is_dir", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::PathBuf::is_file", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::PathBuf::is_symlink", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::PathBuf::metadata", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::PathBuf::read_dir", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::PathBuf::read_link", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::PathBuf::symlink_metadata", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::path::PathBuf::try_exists", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::canonicalize", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::copy", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::create_dir", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::create_dir_all", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::hard_link", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::metadata", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::read", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::read_dir", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::read_link", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::read_to_string", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::remove_dir", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::remove_dir_all", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::remove_file", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::rename", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::set_permissions", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::symlink_metadata", reason = "File system operations should be done using the sys_traits crate" },
  { path = "std::fs::write", reason = "File system operations should be done using the sys_traits crate" }
]
disallowed-types = [
  "swc_common::BytePos",
  "swc_common::Span",
  "swc_common::Spanned",
]
